### ISSUE TITLE
can't reopen port after port was closed

### ISSUE THREAD

**Issue by blurks** [patrickkidd/pyrtmidi#22]
Hi,

I noticed, after you close a port, you get an error when you try to reopen it. The following code reproduces this behavior.

```python
import rtmidi
m = rtmidi.RtMidiIn()
m.openPort(0) # first call works
m.closePort()
m.openPort(0) # second call fails
```
I get the following error:

```
MidiInAlsa::openPort: ALSA error making port connection.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rtmidi.Error: MidiInAlsa::openPort: ALSA error making port connection.
```

My OS is ArchLinux, pyrtmidi 2.3.4-2.

I hope I didn't miss anything, but I couldn't find any documentation on this behavior. So I decided to report it.  This might also be a problem of RtMidi. But as I am not very familiar with C++, I didn't check it.

**Comment by patrickkidd** [comment]
That behavior is from `RtMidi`, which means that `pyrtmidi` is functioning properly. The suggested use is to create a new RtMidi object and open a port on it instead.
