### ISSUE TITLE
Fails to detect Midi Inputs 

### ISSUE THREAD

**Issue by alandrees** [patrickkidd/pyrtmidi#3]
I am using pyrtmidi on the raspberry pi, and it doesn't seem to be able to detect the Midi inputs (I'm not using outputs for this project, so I can't speak on that).

The curious thing about it is that the C/C++ RtMidi library seems to work.

My hardware is a Raspberry Pi Model B with an EMU XMidi 1x1.

**Comment by patrickkidd** [comment]
Which audio platform does the raspberry pi use, and what version of the c++ code did you try? Maybe compare build flags between pyrtmidi and your c++ test project's flags?

**Comment by PH0MB** [comment]
As far as I understand there are 3 possible rtmidi python wrapper libraries available
python-rtmidi 0.5.b1
pyrtmidi 2.2 (this one)
rtmidi-python 0.2.2
I had this particular problem too running the pip install rtmidi on Raspian Jessie Light. There were some issues with the compiler on some include  I copied the repository tarball and compiled by hand, but the build 
I could install the python-rtmidi  and got it working out of the box.
So there must be something wrong on Raspian in combination with pyrtmidi and the pip install command. I'm pretty confident I have all the prerequisites loaded on the Pi.

**Comment by patrickkidd** [comment]
I'm not familiar with raspberry pi as to the midi architecture. pyrtmidi uses the RtMidi library, so if it compiles and runs but does not detect devices then raspberry pi may not be supported. However, I just updated then package to work with pypi so you may try it again. I am closing this issue for now.
